In [4]:
# This Python file uses the following encoding: utf-8
from PyQt6 import QtCore

import pickle
import os


def make_index(file):
    origins = []
    current_origin = 0

    original_position = file.tell()
    file.seek(0)

    while True:
        try:
            pickle.load(file)
            origins.append(current_origin)
            current_origin = file.tell()
        except EOFError:
            break

    file.seek(original_position)

    return origins

class DaqFile(QtCore.QObject):
    # Provides appending and random access to pickled objects in a file

    def __init__(self, filename):
        super().__init__()
        self.filename = filename
        self.origins = None
        self.file = None

    def record(self):
        #does record require us to pickle??
        if(os.path.exists(self.filename)):
            print("Cannot overwrite an existing file")
            return
        self.file = open(self.filename, 'a+b')
        self.file = make_index(self.file)

    def playback(self):
        try:
            self.file = open(self.filename, 'r+b')
        except Exception as e:
            print(f"Exception: {e} in daqfile for playback")
            raise

        self.origins = make_index(self.file)
        return True

    def count(self):
        print(self.origins)
        print(type(self.origins))
        return len(self.origins)

    def get(self, n):
        self.file.seek(self.origins[n])
        return pickle.load(self.file)

    def append(self, obj):
        original_position = self.file.tell()

        self.file.seek(0, os.SEEK_END)
        self.origins.append(self.file.tell())
        pickle.dump(obj, self.file)

        self.file.seek(original_position)

    def seek(self, index):
        self.file.seek(self.origins[index])

    def next(self):
        # may throw EOFError
        return pickle.load(self.file)

    def close(self):
        self.file.close()


In [11]:
daqfile = DaqFile('C:\\Users\\MichaelKolb\\Downloads\\2024.02.29-14.26.55.npy')
print(type(daqfile))
print(daqfile)
daqfile.playback()
print(daqfile.count())

<class '__main__.DaqFile'>
[0, 390352, 780704, 1171056, 1561408, 1951760, 2342112, 2732464, 3122816, 3513168, 3903520, 4293872, 4684224, 5074576, 5464928, 5855280, 6245632, 6635984, 7026336, 7416688, 7807040, 8197392, 8587744, 8978096, 9368448, 9758800, 10149152, 10539504, 10929856, 11320208, 11710560, 12100912, 12491264, 12881616, 13271968, 13662320, 14052672, 14443024, 14833376, 15223728, 15614080, 16004432, 16394784, 16785136, 17175488, 17565840, 17956192, 18346544, 18736896, 19127248, 19517600, 19907952, 20298304, 20688656, 21079008, 21469360, 21859712, 22250064, 22640416, 23030768, 23421120, 23811472, 24201824, 24592176, 24982528, 25372880, 25763232, 26153584, 26543936, 26934288, 27324640, 27714992, 28105344, 28495696, 28886048, 29276400, 29666752, 30057104, 30447456, 30837808, 31228160, 31618512, 32008864, 32399216, 32789568, 33179920, 33570272, 33960624, 34350976, 34741328, 35131680, 35522032, 35912384, 36302736, 36693088, 37083440, 37473792, 37864144, 38254496, 38644848, 390352

In [12]:
import os

# unpacking the tuple
file_name, file_extension = os.path.splitext("/Users/pankaj/abc.txt")

print(file_name)
print(file_extension)

print(os.path.splitext("/Users/pankaj/.bashrc"))
print(os.path.splitext("/Users/pankaj/a.b/image.png"))

/Users/pankaj/abc
.txt
('/Users/pankaj/.bashrc', '')
('/Users/pankaj/a.b/image', '.png')


In [5]:
import pyqtgraph
from pyqtgraph.graphicsItems.ROI import ROI
from PyQt6.QtGui import QPainterPath

##NOTE: From pyqtgraph's implementation of ImageView
class PlotROI(ROI):
    def __init__(self, size, possize, randitem):
        super().__init__()
        pass
        #print(f"plotroi: {self} {size} {possize} {randitem}")
        #ROI.__init__(self, pos=[0,0], size=size) #, scaleSnap=True, translateSnap=True)
        #self.addScaleHandle([1, 1], [0, 0])
        #self.addRotateHandle([0, 0], [0.5, 0.5])

In [6]:
p = QPainterPath()
p.setElementPositionAt()
# p.currentPosition()
# print(p.contin)

TypeError: setElementPositionAt(self, i: int, x: float, y: float): not enough arguments

In [8]:
user_input = "Stop"
user_input = user_input.split()
print(type(user_input[0]))

<class 'str'>


In [2]:
pts = [[0.007122377202069383, 0.004009986652777811], [0.007959604679354998, 0.0022649879982193396], [0.009555946605858021, 0.003336888776756654]]
print(pts[0:])
print(pts[:][1:])

[[0.007122377202069383, 0.004009986652777811], [0.007959604679354998, 0.0022649879982193396], [0.009555946605858021, 0.003336888776756654]]
[[0.007959604679354998, 0.0022649879982193396], [0.009555946605858021, 0.003336888776756654]]


In [2]:
lol = [
    [1,2,3],
    [4,5,6],
    [7,8,9],
]
# tuple will have to have a print statement
# print(lol[[2],[2],[2]])

TypeError: list indices must be integers or slices, not tuple

In [9]:
import zmq

print(zmq.POLLOUT)
print(zmq.POLLIN)
print(zmq.POLLOUT|zmq.POLLIN)
track = zmq.MessageTracker()
print(not track.done)

2
1
3
False


In [10]:
import time
import datetime
finish = []

for x in range(1000):
    start = time.time_ns()
    datetime.datetime.now()
    finish.append(time.time_ns() - start)

tot = sum(finish)
avg = tot / len(finish)
print(f"total {tot} ns, average {avg} ns")

total 998400 ns, average 998.4 ns


In [6]:
import numpy as np
turbo_colormap_data = np.array(
                      [[0.18995,0.07176,0.23217],
                       [0.19483,0.08339,0.26149],
                       [0.19956,0.09498,0.29024],
                       [0.20415,0.10652,0.31844],
                       [0.20860,0.11802,0.34607],
                       [0.21291,0.12947,0.37314],
                       [0.21708,0.14087,0.39964],
                       [0.22111,0.15223,0.42558],
                       [0.22500,0.16354,0.45096],
                       [0.22875,0.17481,0.47578],
                       [0.23236,0.18603,0.50004],
                       [0.23582,0.19720,0.52373],
                       [0.23915,0.20833,0.54686],
                       [0.24234,0.21941,0.56942],
                       [0.24539,0.23044,0.59142],
                       [0.24830,0.24143,0.61286],
                       [0.25107,0.25237,0.63374],
                       [0.25369,0.26327,0.65406],
                       [0.25618,0.27412,0.67381],
                       [0.25853,0.28492,0.69300],
                       [0.26074,0.29568,0.71162],
                       [0.26280,0.30639,0.72968],
                       [0.26473,0.31706,0.74718],
                       [0.26652,0.32768,0.76412],
                       [0.26816,0.33825,0.78050],
                       [0.26967,0.34878,0.79631],
                       [0.27103,0.35926,0.81156],
                       [0.27226,0.36970,0.82624],
                       [0.27334,0.38008,0.84037],
                       [0.27429,0.39043,0.85393],
                       [0.27509,0.40072,0.86692],
                       [0.27576,0.41097,0.87936],
                       [0.27628,0.42118,0.89123],
                       [0.27667,0.43134,0.90254],
                       [0.27691,0.44145,0.91328],
                       [0.27701,0.45152,0.92347],
                       [0.27698,0.46153,0.93309],
                       [0.27680,0.47151,0.94214],
                       [0.27648,0.48144,0.95064],
                       [0.27603,0.49132,0.95857],
                       [0.27543,0.50115,0.96594],
                       [0.27469,0.51094,0.97275],
                       [0.27381,0.52069,0.97899],
                       [0.27273,0.53040,0.98461],
                       [0.27106,0.54015,0.98930],
                       [0.26878,0.54995,0.99303],
                       [0.26592,0.55979,0.99583],
                       [0.26252,0.56967,0.99773],
                       [0.25862,0.57958,0.99876],
                       [0.25425,0.58950,0.99896],
                       [0.24946,0.59943,0.99835],
                       [0.24427,0.60937,0.99697],
                       [0.23874,0.61931,0.99485],
                       [0.23288,0.62923,0.99202],
                       [0.22676,0.63913,0.98851],
                       [0.22039,0.64901,0.98436],
                       [0.21382,0.65886,0.97959],
                       [0.20708,0.66866,0.97423],
                       [0.20021,0.67842,0.96833],
                       [0.19326,0.68812,0.96190],
                       [0.18625,0.69775,0.95498],
                       [0.17923,0.70732,0.94761],
                       [0.17223,0.71680,0.93981],
                       [0.16529,0.72620,0.93161],
                       [0.15844,0.73551,0.92305],
                       [0.15173,0.74472,0.91416],
                       [0.14519,0.75381,0.90496],
                       [0.13886,0.76279,0.89550],
                       [0.13278,0.77165,0.88580],
                       [0.12698,0.78037,0.87590],
                       [0.12151,0.78896,0.86581],
                       [0.11639,0.79740,0.85559],
                       [0.11167,0.80569,0.84525],
                       [0.10738,0.81381,0.83484],
                       [0.10357,0.82177,0.82437],
                       [0.10026,0.82955,0.81389],
                       [0.09750,0.83714,0.80342],
                       [0.09532,0.84455,0.79299],
                       [0.09377,0.85175,0.78264],
                       [0.09287,0.85875,0.77240],
                       [0.09267,0.86554,0.76230],
                       [0.09320,0.87211,0.75237],
                       [0.09451,0.87844,0.74265],
                       [0.09662,0.88454,0.73316],
                       [0.09958,0.89040,0.72393],
                       [0.10342,0.89600,0.71500],
                       [0.10815,0.90142,0.70599],
                       [0.11374,0.90673,0.69651],
                       [0.12014,0.91193,0.68660],
                       [0.12733,0.91701,0.67627],
                       [0.13526,0.92197,0.66556],
                       [0.14391,0.92680,0.65448],
                       [0.15323,0.93151,0.64308],
                       [0.16319,0.93609,0.63137],
                       [0.17377,0.94053,0.61938],
                       [0.18491,0.94484,0.60713],
                       [0.19659,0.94901,0.59466],
                       [0.20877,0.95304,0.58199],
                       [0.22142,0.95692,0.56914],
                       [0.23449,0.96065,0.55614],
                       [0.24797,0.96423,0.54303],
                       [0.26180,0.96765,0.52981],
                       [0.27597,0.97092,0.51653],
                       [0.29042,0.97403,0.50321],
                       [0.30513,0.97697,0.48987],
                       [0.32006,0.97974,0.47654],
                       [0.33517,0.98234,0.46325],
                       [0.35043,0.98477,0.45002],
                       [0.36581,0.98702,0.43688],
                       [0.38127,0.98909,0.42386],
                       [0.39678,0.99098,0.41098],
                       [0.41229,0.99268,0.39826],
                       [0.42778,0.99419,0.38575],
                       [0.44321,0.99551,0.37345],
                       [0.45854,0.99663,0.36140],
                       [0.47375,0.99755,0.34963],
                       [0.48879,0.99828,0.33816],
                       [0.50362,0.99879,0.32701],
                       [0.51822,0.99910,0.31622],
                       [0.53255,0.99919,0.30581],
                       [0.54658,0.99907,0.29581],
                       [0.56026,0.99873,0.28623],
                       [0.57357,0.99817,0.27712],
                       [0.58646,0.99739,0.26849],
                       [0.59891,0.99638,0.26038],
                       [0.61088,0.99514,0.25280],
                       [0.62233,0.99366,0.24579],
                       [0.63323,0.99195,0.23937],
                       [0.64362,0.98999,0.23356],
                       [0.65394,0.98775,0.22835],
                       [0.66428,0.98524,0.22370],
                       [0.67462,0.98246,0.21960],
                       [0.68494,0.97941,0.21602],
                       [0.69525,0.97610,0.21294],
                       [0.70553,0.97255,0.21032],
                       [0.71577,0.96875,0.20815],
                       [0.72596,0.96470,0.20640],
                       [0.73610,0.96043,0.20504],
                       [0.74617,0.95593,0.20406],
                       [0.75617,0.95121,0.20343],
                       [0.76608,0.94627,0.20311],
                       [0.77591,0.94113,0.20310],
                       [0.78563,0.93579,0.20336],
                       [0.79524,0.93025,0.20386],
                       [0.80473,0.92452,0.20459],
                       [0.81410,0.91861,0.20552],
                       [0.82333,0.91253,0.20663],
                       [0.83241,0.90627,0.20788],
                       [0.84133,0.89986,0.20926],
                       [0.85010,0.89328,0.21074],
                       [0.85868,0.88655,0.21230],
                       [0.86709,0.87968,0.21391],
                       [0.87530,0.87267,0.21555],
                       [0.88331,0.86553,0.21719],
                       [0.89112,0.85826,0.21880],
                       [0.89870,0.85087,0.22038],
                       [0.90605,0.84337,0.22188],
                       [0.91317,0.83576,0.22328],
                       [0.92004,0.82806,0.22456],
                       [0.92666,0.82025,0.22570],
                       [0.93301,0.81236,0.22667],
                       [0.93909,0.80439,0.22744],
                       [0.94489,0.79634,0.22800],
                       [0.95039,0.78823,0.22831],
                       [0.95560,0.78005,0.22836],
                       [0.96049,0.77181,0.22811],
                       [0.96507,0.76352,0.22754],
                       [0.96931,0.75519,0.22663],
                       [0.97323,0.74682,0.22536],
                       [0.97679,0.73842,0.22369],
                       [0.98000,0.73000,0.22161],
                       [0.98289,0.72140,0.21918],
                       [0.98549,0.71250,0.21650],
                       [0.98781,0.70330,0.21358],
                       [0.98986,0.69382,0.21043],
                       [0.99163,0.68408,0.20706],
                       [0.99314,0.67408,0.20348],
                       [0.99438,0.66386,0.19971],
                       [0.99535,0.65341,0.19577],
                       [0.99607,0.64277,0.19165],
                       [0.99654,0.63193,0.18738],
                       [0.99675,0.62093,0.18297],
                       [0.99672,0.60977,0.17842],
                       [0.99644,0.59846,0.17376],
                       [0.99593,0.58703,0.16899],
                       [0.99517,0.57549,0.16412],
                       [0.99419,0.56386,0.15918],
                       [0.99297,0.55214,0.15417],
                       [0.99153,0.54036,0.14910],
                       [0.98987,0.52854,0.14398],
                       [0.98799,0.51667,0.13883],
                       [0.98590,0.50479,0.13367],
                       [0.98360,0.49291,0.12849],
                       [0.98108,0.48104,0.12332],
                       [0.97837,0.46920,0.11817],
                       [0.97545,0.45740,0.11305],
                       [0.97234,0.44565,0.10797],
                       [0.96904,0.43399,0.10294],
                       [0.96555,0.42241,0.09798],
                       [0.96187,0.41093,0.09310],
                       [0.95801,0.39958,0.08831],
                       [0.95398,0.38836,0.08362],
                       [0.94977,0.37729,0.07905],
                       [0.94538,0.36638,0.07461],
                       [0.94084,0.35566,0.07031],
                       [0.93612,0.34513,0.06616],
                       [0.93125,0.33482,0.06218],
                       [0.92623,0.32473,0.05837],
                       [0.92105,0.31489,0.05475],
                       [0.91572,0.30530,0.05134],
                       [0.91024,0.29599,0.04814],
                       [0.90463,0.28696,0.04516],
                       [0.89888,0.27824,0.04243],
                       [0.89298,0.26981,0.03993],
                       [0.88691,0.26152,0.03753],
                       [0.88066,0.25334,0.03521],
                       [0.87422,0.24526,0.03297],
                       [0.86760,0.23730,0.03082],
                       [0.86079,0.22945,0.02875],
                       [0.85380,0.22170,0.02677],
                       [0.84662,0.21407,0.02487],
                       [0.83926,0.20654,0.02305],
                       [0.83172,0.19912,0.02131],
                       [0.82399,0.19182,0.01966],
                       [0.81608,0.18462,0.01809],
                       [0.80799,0.17753,0.01660],
                       [0.79971,0.17055,0.01520],
                       [0.79125,0.16368,0.01387],
                       [0.78260,0.15693,0.01264],
                       [0.77377,0.15028,0.01148],
                       [0.76476,0.14374,0.01041],
                       [0.75556,0.13731,0.00942],
                       [0.74617,0.13098,0.00851],
                       [0.73661,0.12477,0.00769],
                       [0.72686,0.11867,0.00695],
                       [0.71692,0.11268,0.00629],
                       [0.70680,0.10680,0.00571],
                       [0.69650,0.10102,0.00522],
                       [0.68602,0.09536,0.00481],
                       [0.67535,0.08980,0.00449],
                       [0.66449,0.08436,0.00424],
                       [0.65345,0.07902,0.00408],
                       [0.64223,0.07380,0.00401],
                       [0.63082,0.06868,0.00401],
                       [0.61923,0.06367,0.00410],
                       [0.60746,0.05878,0.00427],
                       [0.59550,0.05399,0.00453],
                       [0.58336,0.04931,0.00486],
                       [0.57103,0.04474,0.00529],
                       [0.55852,0.04028,0.00579],
                       [0.54583,0.03593,0.00638],
                       [0.53295,0.03169,0.00705],
                       [0.51989,0.02756,0.00780],
                       [0.50664,0.02354,0.00863],
                       [0.49321,0.01963,0.00955],
                       [0.47960,0.01583,0.01055],
                       [1,1,1]])

# turbo_colormap_data = turbo_colormap_data*255
y = 257 // 42
for x in range (257):
    if (x % y) == 0:
        print(turbo_colormap_data[x])

[0.18995 0.07176 0.23217]
[0.21708 0.14087 0.39964]
[0.23915 0.20833 0.54686]
[0.25618 0.27412 0.67381]
[0.26816 0.33825 0.7805 ]
[0.27509 0.40072 0.86692]
[0.27698 0.46153 0.93309]
[0.27381 0.52069 0.97899]
[0.25862 0.57958 0.99876]
[0.22676 0.63913 0.98851]
[0.18625 0.69775 0.95498]
[0.14519 0.75381 0.90496]
[0.11167 0.80569 0.84525]
[0.09377 0.85175 0.78264]
[0.09958 0.8904  0.72393]
[0.13526 0.92197 0.66556]
[0.19659 0.94901 0.59466]
[0.27597 0.97092 0.51653]
[0.36581 0.98702 0.43688]
[0.45854 0.99663 0.3614 ]
[0.54658 0.99907 0.29581]
[0.62233 0.99366 0.24579]
[0.68494 0.97941 0.21602]
[0.74617 0.95593 0.20406]
[0.80473 0.92452 0.20459]
[0.85868 0.88655 0.2123 ]
[0.90605 0.84337 0.22188]
[0.94489 0.79634 0.228  ]
[0.97323 0.74682 0.22536]
[0.98986 0.69382 0.21043]
[0.99654 0.63193 0.18738]
[0.99419 0.56386 0.15918]
[0.9836  0.49291 0.12849]
[0.96555 0.42241 0.09798]
[0.94084 0.35566 0.07031]
[0.91024 0.29599 0.04814]
[0.87422 0.24526 0.03297]
[0.83172 0.19912 0.02131]
[0.7826  0.1

In [7]:
# importing PyQt6
import PyQt6
from PyQt6 import QtGui, QtWidgets, QtCore
 
# importing system
import sys
import random
 
# importing numpy as np
import numpy as np
 
# importing pyqtgraph as pg
import pyqtgraph as pg


color_lost = []


# Create some random numbers
# n = 100000
# x = np.random.randn(n)
# y = (1.5 * x) + np.random.randn(n)

x = [[] for ct in range(42)]
for ct in range(42):
    for y in range(10):
        if 5 < y < 9:
            x[ct].append(y*(random.randrange(1,10)*(random.randrange(1,4))))
        else:
            x[ct].append(0)

# print(x)
print(x)
x = np.array(x)
#2D heatmap of 42 channels vs some number of bins up and down

# Estimate the 2D histogram
# nbins = 200
# H, xedges, yedges = np.histogram2d(x,y,bins=nbins)

# H needs to be rotated and flipped
# H = np.rot90(H)
# H = np.flipud(H)

# Hmasked = np.ma.masked_where(H==0,H)


plot = pg.plot()
plot.setBackground('w')
plot.setXRange(0,42)
plot.setYRange(0,10)
# plot.setlimits(xMin=0,xMax=nbins,yMin=0,yMax=nbins)

# tr = QtGui.QTransform()  # prepare ImageItem transformation:
# tr.scale(6.0, 3.0)       # scale horizontal and vertical axes
# tr.translate(-1.5, -1.5) # move 3x3 image to locate center at axis origin

# image = np.eye(3)
# print(image)

# img = pg.ImageItem( image, levels=(0,1) ) # create example image
img = pg.ImageItem(x, levels=(0,1))
#need to set a color map that is probably about 500 colors long at least or set it so that at like 500 events it changes colors
turbo_colormap_data = turbo_colormap_data * 255
color = turbo_colormap_data[::-1]
cmap = pg.ColorMap(pos=None, color=color)

# print(pg.colormap.get('CET-L19'))
# img.setColorMap(pg.colormap.get('turbo'))
img.setColorMap(cmap)
img.setLevels((0,255))

plot.addItem( img )  # add ImageItem to PlotItem
plot.showAxes(True)  # frame it with a full set of axes
plot.invertY(False)   # vertical axis counts top to bottom

QtWidgets.QApplication.exec()

[[0, 0, 0, 0, 0, 0, 48, 126, 40, 0], [0, 0, 0, 0, 0, 0, 30, 49, 144, 0], [0, 0, 0, 0, 0, 0, 96, 21, 48, 0], [0, 0, 0, 0, 0, 0, 42, 56, 8, 0], [0, 0, 0, 0, 0, 0, 42, 21, 64, 0], [0, 0, 0, 0, 0, 0, 24, 56, 144, 0], [0, 0, 0, 0, 0, 0, 36, 63, 56, 0], [0, 0, 0, 0, 0, 0, 72, 14, 72, 0], [0, 0, 0, 0, 0, 0, 72, 126, 48, 0], [0, 0, 0, 0, 0, 0, 18, 28, 48, 0], [0, 0, 0, 0, 0, 0, 12, 84, 168, 0], [0, 0, 0, 0, 0, 0, 54, 28, 64, 0], [0, 0, 0, 0, 0, 0, 18, 49, 48, 0], [0, 0, 0, 0, 0, 0, 24, 14, 192, 0], [0, 0, 0, 0, 0, 0, 18, 112, 168, 0], [0, 0, 0, 0, 0, 0, 108, 21, 56, 0], [0, 0, 0, 0, 0, 0, 60, 63, 72, 0], [0, 0, 0, 0, 0, 0, 18, 105, 192, 0], [0, 0, 0, 0, 0, 0, 84, 21, 32, 0], [0, 0, 0, 0, 0, 0, 24, 147, 56, 0], [0, 0, 0, 0, 0, 0, 108, 63, 64, 0], [0, 0, 0, 0, 0, 0, 72, 168, 96, 0], [0, 0, 0, 0, 0, 0, 72, 98, 80, 0], [0, 0, 0, 0, 0, 0, 48, 28, 112, 0], [0, 0, 0, 0, 0, 0, 30, 35, 80, 0], [0, 0, 0, 0, 0, 0, 90, 42, 24, 0], [0, 0, 0, 0, 0, 0, 144, 7, 128, 0], [0, 0, 0, 0, 0, 0, 90, 147, 96, 0], [0,

0

In [4]:
x = [0 for ct in range(42)]
print(x)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [13]:
# importing PyQt6
import PyQt6
from PyQt6 import QtGui, QtWidgets, QtCore
 
# importing system
import sys
 
# importing numpy as np
import numpy as np
 
# importing pyqtgraph as pg
import pyqtgraph as pg


color_lost = []


# Create some random numbers
n = 100000
x = np.random.randn(n)
y = (1.5 * x) + np.random.randn(n)

# Estimate the 2D histogram
nbins = 200
H, xedges, yedges = np.histogram2d(x,y,bins=nbins)

# H needs to be rotated and flipped
H = np.rot90(H)
H = np.flipud(H)

# Hmasked = np.ma.masked_where(H==0,H)


# plot = pg.PlotWidget()
plot = pg.plot()
plot.setBackground('w')
plot.setXRange(0,nbins)
plot.setYRange(0,nbins)
# plot.setlimits(xMin=0,xMax=nbins,yMin=0,yMax=nbins)

# tr = QtGui.QTransform()  # prepare ImageItem transformation:
# tr.scale(6.0, 3.0)       # scale horizontal and vertical axes
# tr.translate(-1.5, -1.5) # move 3x3 image to locate center at axis origin

# image = np.eye(3)
# print(image)

# img = pg.ImageItem( image, levels=(0,1) ) # create example image
img = pg.ImageItem(H, levels=[0,50])
#need to set a color map that is probably about 500 colors long at least or set it so that at like 500 events it changes colors
print(f"H: {H}")
newcolorlist=[(0,0,0)]
# newcolorlist2=[]
# newcolorlist3=[]
# [dark purple -> light blue -> light green -> yellow -> orange -> red]
# for x in range(0,256,16):
#     newcolorlist.append(((255-x),(255-x),(255)))
# for x in range(0,256,16):
#     newcolorlist.append(((0),(255-x),(0)))
# for x in range(0,256,8):
#     newcolorlist.append(((255),(x),(0)))
# for x in range(0,256,8):
#     newcolorlist.append(((255),(255),(x)))
# newcolorlist.extend(newcolorlist2)
# newcolorlist = newcolorlist.reverse()
# print(newcolorlist.reverse())
# newcolorlist.reverse()
# print(f"len turbo color map: {len(turbo_colormap_data)}") # 257 total items 
color = turbo_colormap_data[::-1]
cmap = pg.ColorMap(pos=None, color=color)
print(cmap[1].name())

# print(pg.colormap.get('CET-L19'))
# img.setColorMap(pg.colormap.get('turbo'))
img.setColorMap(cmap)
# img.setLevels((0,255))
# img = pg.ImageItem( image, levels=[[minR, maxR], [minG, maxG], [minB, maxB]] ) # create example image
# img.setTransform(tr) # assign transform

plot.addItem( img )  # add ImageItem to PlotItem
plot.showAxes(True)  # frame it with a full set of axes
plot.invertY(False)   # vertical axis counts top to bottom

QtWidgets.QApplication.exec()

H: [[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
#000000


0

In [14]:
setup = np.array(
   [[244,67,54],
    [233,30,99],
    [156,39,176],
    [103,58,183],
    [63,81,181],
    [33,150,243],
    [0,150,136],
    [139,195,74],
    [255,235,59],
    [255,152,0],
    [255,87,34],
    [30,50,56]])
setup = setup/255
# print(setup)
listo = ["key", "top", "old"]
print(listo.index("old"))

2


In [15]:
import colorcet as cc
from colorcet.plotting import swatch, swatches
import holoviews as hv
hv.extension('matplotlib')
from matplotlib.cm import get_cmap

# get_cmap("cet_fire")
# swatch('fire')


# colorlist = ['%06X' % idx for idx in range(0x8000, 0xffff)]
colorlist = ['#%06x' % idx for idx in range(0xff0000, 0xffffff, 0x000300)]
colorlist2 = ['#%06x' % idx for idx in range(0xffff00, 0xffffff, 0x000003)]
newcolorlist=[]
newcolorlist2=[]
for x in range(0,255,3):
    newcolorlist.append(((255),(x),(0)))
for x in range(0,255,3):
    newcolorlist2.append(((255),(255),(x)))
# print(colorlist)
# print(colorlist2)
# cmap=colorlist
colorlist.extend(colorlist2)
newcolorlist.extend(newcolorlist2)
print(newcolorlist)
# print(colorlist2)
print(len(colorlist))
swatch(name='custom', cmap=colorlist)

ModuleNotFoundError: No module named 'colorcet'

In [16]:
data = {'pos': (0.00025905, 0.00295525)}
print(type(data['pos']))

<class 'tuple'>


In [45]:
import configparser as cfp
import sys
import os
import numpy as np

config = cfp.ConfigParser()

if os.path.exists('test.ini'):
    config.read('test.ini')
else:
    config['adc_channels'] = {}
    config['photon_channels'] = {}
    for i in range(12):
        config['adc_channels'][f'channel {i}'] = '0 nm'
        config['photon_channels'][f'channel {i}'] = '0 nm'
    with open('test.ini', 'w') as configfile:
        config.write(configfile)


tempsections = config.sections()
if 'adc_channels' and 'photon_channels' not in tempsections:
    print("Error")

print(config.sections())
temp = config.items('adc_channels')
print(len(temp))
x,y = np.shape(temp)
print(f"x,y: {x}, {y}")
print(temp[0])

# for i in range(12):
#     config['adc_channels'][f'channel {i}'] = '100 nm'
#     config['photon_channels'][f'channel {i}'] = '100 nm'
# with open(f'test.ini{x}', 'w') as configfile:
#     config.write(configfile)
adc_channels = config.items('adc_channels')
templist = [adc_channels[x][-1] for x in range(len(adc_channels))]
print(templist)


['adc_channels', 'photon_channels']
12
x,y: 12, 2
('channel 0', '100 nm')
['100 nm', '100 nm', '100 nm', '100 nm', '100 nm', '100 nm', '100 nm', '100 nm', '100 nm', '100 nm', '100 nm', '100 nm']


In [14]:
import configparser
config = configparser.ConfigParser()
config['DEFAULT'] = {'ServerAliveInterval': '45',
                     'Compression': 'yes',
                     'CompressionLevel': '9'}
config['forge.example'] = {}
config['forge.example']['User'] = 'hg'
config['topsecret.server.example'] = {}
topsecret = config['topsecret.server.example']
topsecret['Port'] = '50022'     # mutates the parser
topsecret['ForwardX11'] = 'no'  # same here
config['DEFAULT']['ForwardX11'] = 'yes'
with open('example.ini', 'w') as configfile:
  config.write(configfile)

In [47]:
import PyQt6
from PyQt6.QtWidgets import QCheckBox

tempBox = QCheckBox()
# tempBox.setText()
tempBox.set


AttributeError: 'list' object has no attribute 'Text'

In [ ]:
CRITICAL = True
ERROR = True
WARNING = True
def safeprint(string, type):
    if not CRITICAL:
        return
    if type == "ERROR" and ERROR:
        print(f"ERROR: {string}")
    if type == "WARNING":
        print(f"WARNING: {string}")


In [3]:
import zmq
print(zmq.POLLIN)

1


In [1]:
products = ['none', 'first', 'second']

while products:
    print(products[-1])
    products.pop()


second
first
none


In [9]:
products = {}
products["serialn"] = [1]
products["data"] = {}
products["data"]["adc_data"] = [ [0,0,0],[0,0,0],[0,0,0] ]
products["data"]["count_data"] = [ [0,0,0],[0,0,0],[0,0,0] ]
print(products)

products["serialn"].append(2)
products["data"]["adc_data"].extend([[1,1,1],[1,1,1],[1,1,1]])
# products["data"]["adc_data"].append([[1,1,1],[1,1,1],[1,1,1]])
products["data"]["count_data"].extend([[1,1,1],[1,1,1],[1,1,1]])
print(products)

{'serialn': [1], 'data': {'adc_data': [[0, 0, 0], [0, 0, 0], [0, 0, 0]], 'count_data': [[0, 0, 0], [0, 0, 0], [0, 0, 0]]}}
{'serialn': [1, 2], 'data': {'adc_data': [[0, 0, 0], [0, 0, 0], [0, 0, 0], [1, 1, 1], [1, 1, 1], [1, 1, 1]], 'count_data': [[0, 0, 0], [0, 0, 0], [0, 0, 0], [1, 1, 1], [1, 1, 1], [1, 1, 1]]}}


In [46]:
import sys
output = {}
output["adc_data"] = {}
output["count_data"] = {}
output["adc_data"]["peak"] = []
output["adc_data"]["area"] = []
output["adc_data"]["width"] = []
output["count_data"]["peak"] = []
output["count_data"]["area"] = []
output["count_data"]["width"] = []
output["count_data"]["total"] = []
for n in range(42):
    if len(output["adc_data"]["peak"]) < (n+1):
        output["adc_data"]["peak"].append([])
        output["adc_data"]["area"].append([])
        output["adc_data"]["width"].append([])
        output["count_data"]["peak"].append([])
        output["count_data"]["area"].append([])
        output["count_data"]["width"].append([])
        output["count_data"]["total"].append([])
#Just above is 184 bytes
for t in range (2500):
    for n in range(42):
        output["adc_data"]["peak"][n].append(65535)

total_size = sys.getsizeof(output["adc_data"]["peak"][0]) * 42 * 4 * 2500
print(output["adc_data"]["peak"].index(max(output["adc_data"]["peak"])))
gb_size = 1000000000
print(total_size)
print(total_size/gb_size)
# print(sys.getsizeof(output["adc_data"]["peak"]) * 7 * 2500)

0
8625120000
8.62512


In [45]:
import numpy as np
from scipy.stats import mode as mode
ch = [1,3,5,7,2,6,15,22,16,17,15,15,15,2,2,2,2,2,2,2,2,2]
print(f"mean: {np.mean(ch)}")
print(f"mode: {mode(ch)[0]}")
norm = ch-mode(ch)[0]
print(norm)
print(sum(norm))
print(ch.index(max(ch)))
# adc_max_index.append(input["adc_data"].index(max(input["adc_data"][:,n])))


mean: 7.136363636363637
mode: 2
[-1  1  3  5  0  4 13 20 14 15 13 13 13  0  0  0  0  0  0  0  0  0]
113
7


In [2]:
import time

print(time.time())
print(int(time.time()))

1717616390.5615275
1717616390


In [5]:
import multiprocessing as mp
from multiprocessing import Pool
from multiprocessing.pool import ThreadPool as pool

def f(x):
    return x*x
    
if __name__ == "__main__":
    # p = Pool()
    # p = pool()
    # results = p.map(f, [1,2,3])
    # print(results)
    # p.close()
    # p.join()
    # with Pool(5) as p:
    
    with pool(5) as p:
        print(p.map(f, [1, 2, 3]))
        p.close()
        p.join()

print(f"Number of cpu: {mp.cpu_count()}")

[1, 4, 9]
Number of cpu: 24


In [34]:
import multiprocessing as mp
from multiprocessing import Pool
from multiprocessing.pool import ThreadPool as pool
import random
import time


class testclass:
    def __init__(self):
        self.numbers = [random.randint(1,128) for x in range(10)]
        self.words = ['test', 'quiz', 'book']
        self.encyclopedia = {'channel1' : 'off', 'channel2' : 'on'}
    
    def h(self):
        for item, state in self.encyclopedia.items():
            if state == 'on':
                continue
                # print(f"{item} is on")
            else:
                self.encyclopedia[item] = 'on'
                # print(f"Turnning on {item}")
                self.i()

    def i(self):
        # print(f"normal: {self.numbers}")
        self.numbers.reverse()
        # print(f"reversed: {self.numbers}")

    def j(self):
        # print(f"normal words: {self.words}")
        self.words.reverse()
        # print(f"reversed words: {self.words}")


def g(x):
    x.reverse()

def f(x):
    # return x*x
    # print(x)
    g(x)
    # print(x)
    for ct in range(len(x)):
        x[ct] = (ct%3) * random.randint(1,128) + x[ct]

    print(x)
    
if __name__ == "__main__":
    
    # array1 = [[x for x in range(10)] for ct in range(10)]
    # print(array1)

    # with pool(5) as p:
    #     # print(p.map(f, [1, 2, 3]))
    #     p.map(f, array1)
    #     p.close()
    #     p.join()

    # print(array1)
    timestart = 0
    timeend = 0
    array1 = []
    array2 = []
    for x in range(1000000):
        array1.append(testclass())
        # array2.append(testclass())
    
    # print(array1)
    # for key, value in array1[0].encyclopedia.items():
    #     print(f"item: {key}, state: {value}")

    # timestart = time.time()
    # with pool(5) as p:
    #     p.map(testclass.h, array1)
    #     p.map(testclass.j, array1)
    # timeend = time.time()
    # print(f"Pool runtime: {timeend - timestart}")

    timestart = time.time()
    for i in range(len(array1)):
        array1[i].h()
        array1[i].j()
    timeend = time.time()
    print(f"Non pool runtime: {timeend - timestart}")
    
# Pool runtime: 0.5830783843994141
# Non pool runtime: 0.5050392150878906

1000000
Non pool runtime: 0.5050392150878906
